### PR TITLE
INO match folder name

### PR DESCRIPTION
**Pull request by Defragster**

### CODE REVIEW

**Comment by mjs513** [comment]
Sorry Tim - that was me and my fat fingering :)

**Comment by Defragster** [comment]
Yes, yes it was. I see that now in github.

**Comment by PaulStoffregen** [comment]
Opps, I might have just undone this (got a conflict while committing).  Please sync up and check.

**Comment by mjs513** [comment]
Just checked and looks ok   Also checked in the IDE that names match up

**Pull request merged**
